server:
  port: 8081

spring:
  application:
    name: BBRDesafioMDP
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

custom:
  global:
    commerce: BBR SpA
    user: uBBR
